name: movie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "2.13.4"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.0

  firebase_storage: ^8.0.3
  cloud_firestore: ^1.0.5
  firebase_auth: ^1.1.0
  cached_network_image: ^3.2.0
  lint: ^1.0.0




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

